[tox]
minversion = 4.28.0
requires =
    tox-uv>=1.25
envlist = build, py310, py311, py312, py313, py314, py310-lower-bounds, docs, pyright
isolated_build = true
passenv =
    CI

[testenv]
runner = uv-venv-lock-runner
package = wheel
dependency_groups = test
commands = make test
allowlist_externals =
    make

[testenv:build]
description = Check distribution files
package = skip
dependency_groups = build
commands =
    python -c 'import shutil; shutil.rmtree("{toxinidir}{/}dist", ignore_errors=True)'
    pyproject-build --outdir {toxinidir}{/}dist .
    check-wheel-contents {toxinidir}{/}dist
    twine check {toxinidir}{/}dist{/}*

[testenv:py310-lower-bounds]
description = Run tests with the lowest supported direct dependency versions
runner = uv-venv-runner
uv_resolution = lowest-direct

[testenv:pytest-dev]
description = Run tests against pytest main
runner = uv-venv-runner
deps =
    pytest @ git+https://github.com/pytest-dev/pytest.git

[testenv:docs]
allowlist_externals =
    git
dependency_groups = docs
change_dir = docs
description = Build The Docs with {basepython}
commands =
    # Retrieve possibly missing commits:
    -git fetch --unshallow
    -git fetch --tags

    # Build the html docs with Sphinx:
    {envpython} -Im sphinx \
      -j auto \
      {tty:--color} \
      -a \
      -T \
      -n \
      -W --keep-going \
      -d "{temp_dir}{/}.doctrees" \
      . \
      {posargs:"{envdir}{/}docs_out" -b html}

    # Print out the output docs dir and a way to serve html:
    -{envpython} -c\
    'import pathlib;\
    docs_dir = pathlib.Path(r"{envdir}") / "docs_out";\
    index_file = docs_dir / "index.html";\
    print("\n" + "=" * 120 +\
    f"\n\nOpen the documentation with:\n\n\
    \t$ python3 -Im webbrowser \N\{QUOTATION MARK\}file://\{index_file\}\N\{QUOTATION MARK\}\n\n\
    To serve docs, use\n\n\
    \t$ python3 -Im http.server --directory \
    \N\{QUOTATION MARK\}\{docs_dir\}\N\{QUOTATION MARK\} 0\n\n" +\
    "=" * 120)'
changedir = {toxinidir}{/}docs
isolated_build = true
passenv =
    SSH_AUTH_SOCK
skip_install = false

[testenv:pyright]
package = skip
dependency_groups = typing
commands = pyright pytest_asyncio/ tests/

[gh-actions]
python =
    3.10: py310, py310-lower-bounds, build
    3.11: py311
    3.12: py312
    3.13: py313, pyright
    3.14-dev: py314
    pypy3: pypy3
